[monast]
secret = 
permit=0.0.0.0/0.0.0.0
read = system,call,log,verbose,command,agent,user,config,originate,reporting
write = system,call,log,verbose,command,agent,user,config,originate,reporting
writetimeout = 10