[monast]
secret = 8ad789af361ba9bf76d1866d619b4b82
deny=0.0.0.0/0.0.0.0
permit=172.16.0.0/255.255.255.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate,message
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate,message
writetimeout = 5000