[customer-survey-ivr]
exten => _X.,1,NoOp(Post call survey beginning)
;exten => _X.,n,Playback(whoareyou)
exten => _X.,n,DIAL(PJSIP/${EXTEN},,trg) ; добавляем опцию g - когда вызываемый абонент вешает трубку, мы продолжим выполнение команд далее по текущему контексту.
exten => _X.,n,GotoIf($[${DIALSTATUS}=BUSY]?busy:answer) ; проверяем, был ли отвечен вызов
exten => _X.,n,GotoIf($[${QUEUESTATUS}=TIMEOUT]?timeout:answer)
exten => _X.,n(busy),Hangup()
exten => _X.,n(answer),Goto(assessment,${EXTEN},1)
;exten => _X.,n,Goto(assessment,${EXTEN},1)

[assessment]
exten => _X.,1,Answer
exten => _X.,n,Wait(1)
exten => _X.,n(skip),Set(IVR_MSG=en/beep)
exten => _X.,n(start),Set(TIMEOUT(digit)=1)
exten => _X.,n,Background(/var/lib/asterisk/sounds/en/custom/ontaxi_rate_end,m)  ;озвучиваем предложение об оценке клиенту
exten => _X.,n,Playback(beep)
exten => _X.,n,WaitExten(20,)

exten => 1,1,AGI(survey.php,${CDR(src)},${DIALEDPEERNUMBER},${NODEST},1)
exten => 1,n,Playback(/var/lib/asterisk/sounds/en/custom/ontaxi_ocenka_02,skip)
exten => 1,n,Hangup()

exten => 2,1,AGI(survey.php,${CDR(src)},${DIALEDPEERNUMBER},${NODEST},2)
exten => 2,n,Playback(/var/lib/asterisk/sounds/en/custom/ontaxi_ocenka_02,skip)
exten => 2,n,Hangup()

exten => 3,1,AGI(survey.php,${CDR(src)},${DIALEDPEERNUMBER},${NODEST},3)
exten => 3,n,Playback(/var/lib/asterisk/sounds/en/custom/ontaxi_ocenka_02,skip)
exten => 3,n,Hangup()

exten => 4,1,AGI(survey.php,${CDR(src)},${DIALEDPEERNUMBER},${NODEST},4)
exten => 4,n,Playback(/var/lib/asterisk/sounds/en/custom/ontaxi_ocenka_02,skip)
exten => 4,n,Hangup()

exten => 5,1,AGI(survey.php,${CDR(src)},${DIALEDPEERNUMBER},${NODEST},5)
exten => 5,n,Playback(/var/lib/asterisk/sounds/en/custom/ontaxi_ocenka_02,skip)
exten => 5,n,Hangup()

exten => t,1,NoOp(Timeout - no input)
exten => t,n,Playback(/var/lib/asterisk/sounds/en/custom/ontaxi_ocenka_02,skip)
exten => t,n,Hangup()

exten => e,1,NoOp(Error)
exten => e,n,Playback(/var/lib/asterisk/sounds/en/custom/ontaxi_ocenka_02,skip)
exten => e,n,Hangup()

exten => i,1,NoOp(Invalid input)  ; клиент нажал неверную кнопку
exten => i,n,Goto(_X.,start)      ; повторить с начала