; Example for adding queue sip-users
[98000](+)
member=Local/9809@customer-survey-ivr/n,0,9809 Katerina Rakovets,hint:9809@ext-local

[99000](+)
member=Local/9907@customer-survey-ivr/n,0,9907 Svetlana Yakovleva,hint:9907@ext-local

[12002](+)
member=Local/9907@customer-survey-ivr/n,0,9907 Svetlana Yakovleva,hint:9907@ext-local